### ISSUE TITLE
Bool parameter types are invalid when publishing

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#106]
Publishing breaks when trying to pass in any type other than strings. 

This will break:

```
import rele
rele.publish(topic='foo-bar', data={'baz': 'boo'}, some_flag=True)
```

Returning:

```
File "/usr/local/lib/python3.7/site-packages/rele/publishing.py", line 42, in publish
    _publisher.publish(topic, data, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rele/client.py", line 137, in publish
    future = self._client.publish(topic_path, payload, **attrs)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 261, in publish
    "All attributes being published to Pub/Sub must "
TypeError: All attributes being published to Pub/Sub must be sent as text strings.
```

I propose either:
- adding extra documentation about the limits of the publishing parameters. 
- finding a method in which we can serialize/de-serialize certain types.

**Comment by tobami** [comment]
I would go for the first option. attributes are supposed to be strings, no good to subvert that.

**Comment by luisgc93** [comment]
Isn't this covered in the docs already?
```Note
If you want to publish other types of objects, you may configure the encoder class.

**Comment by andrewgy8** [comment]
No, as I would say that is meant to describe what you can put into the message `data`, not the parameters for publishing itself.
