### ISSUE TITLE
Add message attributes to metrics log

### ISSUE THREAD

**Issue by antoniobusrod** [mercadona/rele#113]
## What?

Logging middleware logs next properties under `metrics`:

1. `agent`
1. `topic`
1. `status`
1. `subscription`

For example, `succeeded` message (`contrib.logging_middleware.LoggingMiddleware.post_process_message_success`).

```
    "levelname": "INFO",
	"message": "Successfully processed message for city-created - city-created-building-factory-spain",
    "module": "logging_middleware",
    "metrics": {
      "name": "subscriptions",
      "data": {
        "agent": "country-maker",
        "topic": "city-created",
        "status": "succeeded",
        "subscription": "city-created-building-factory-spain",
        "duration_seconds": 0.001
      }
    }
```

My proposal is to add a new more property called `attributes` which contains the message attributes.

For example, a `succeeded message would appear as follow:

```
    "levelname": "INFO",
	"message": "Successfully processed message for city-created - city-created-building-factory-spain",
    "module": "logging_middleware",
    "metrics": {
      "name": "subscriptions",
      "data": {
        "agent": "country-maker",
        "topic": "city-created",
        "status": "succeeded",
        "subscription": "city-created-building-factory-spain",
        "duration_seconds": 0.001,
		"attributes": {
			"country": "spain"
		}
      }
    }
```

It would apply for `received`, `failed` and previously mentioned `succeeded` messages.

## Why?

As a real scenario, for a topic, several subscriptions can be registered which only process a message if a message attribute has a particular value.

For example, a topic like `city-created` can have at least four subscriptions:

1. `city-created-building-factory-spain`
1. `city-created-roadway-factory-spain`
1. `city-created-building-factory-portugal`
1. `city-created-roadway-factory-portugal`

`city-created-building-factory-{country}` and `city-created-roadway-factory-{country}` are generic for each country and only process messages when an attribute called `country` matches a defined value like `spain` or `portugal`

The subscriptions run in different environments (`spain` and `portugal`), but logs are consumed in centralized system.

When filtering logs for `spain` environment, there will be logs for messages for all subscriptions (both countries). However, subscriptions for not related country will have a `succeeded` log message with a very short duration (skipped message) and subscriptions for related country will take a bit longer to execute.

If log message metrics contain `attributes`, it would be easy to implement a filter to skip logs from a different country to avoid any noise during log analysis.

**Comment by tobami** [comment]
I guess if you use `attributes` to tag messages to control routing then this would be necessary when it comes to filtering logs. I don't see a big downside since attributes are usually small strings, which may not be the case with messages (which in turn is the reason we didn't add the message in all logs).
