### ISSUE TITLE
Define multiple filters in a subscription

### ISSUE THREAD

**Issue by antoniobusrod** [mercadona/rele#134]
`Subscription` class accepts `filter_by` to be a function that filters the messages to be processed by the sub regarding their attributes.

However, in more than occasion, if a message contains more than one attribute, it would be nice to use a list of filters for each attribute, for example.

I would like to suggest that `filter_by` parameter accepts a list of functions as well.

**Comment by andrewgy8** [comment]
As of now, couldnt you just expand the one filter? Originally you might have
```
def filter_by_foo(kwargs):
    return kwargs.get('foo') == 'baz'
```
But then you want to add another 
```
def filter_by_foo_and_bar(kwargs):
    return (kwargs.get('foo') == 'baz' and kwargs.get('bar') == 'boo')
```

Its not very elegant, but in the meantime that should work. 

I agree that more elegant filtering would be something like

```
def filter_by_foo(kwargs):
    return kwargs.get('foo') == 'awesome'

def filter_by_bar(kwargs):
    return kwargs.get('bar') == 'boo'

@sub('some-topic-name', filter_by=(filter_by_foo, filter_by_bar))
def your_subscription(payload):
   ...
```
