### ISSUE TITLE
Configure Publisher Client timeout

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#136]
I would like to be able to configure the timeout when publishing a message in a blocking fashion. Right now, the default and hard coded way is set to 3.0 seconds. 

I propose adding a configuration so I can declare any number of seconds for the publisher. 

Ex.

```
RELE = {
	...
	'PUBLISHER_TIMEOUT': 5.0
}
```

**Comment by andrewgy8** [comment]
On second thought we could even set the timeout when publishing like:

```
rele.publish('my-topic', data={'foo': 'bar'}, blocking=True, timeout=100.0)
```

**Comment by tobami** [comment]
Indeed, one option does not preclude the other!

**Comment by tobami** [comment]
#137 implements a global timeout, so now we only need to implement it in `.publish()` itself

**Comment by andrewgy8** [comment]
#143 will be in the next release
