### ISSUE TITLE
Execution doesn't stop when using debugger

### ISSUE THREAD

**Issue by daaain** [mercadona/rele#151]
Hey 👋  first of all thanks for this great library!

This might not be a strictly Relé related issue, but when I tried to pause execution to debug some issue (ie dropping a `__import__("pdb").set_trace()`) inside the subscription message handler function it did not stop, but just kept on processing messages.

This might be a trivial problem to overcome, but my search engine fu failed me. I'm guessing the problem is that the subscriber handles the message in a thread, so it would somehow need to let the parent know to stop, but not really sure how to go about it.

**Comment by tobami** [comment]
Happy to know you find Relé useful!

Your assumption is correct. By default, google's library spawns 10 threads per subscription, so pausing one won't be enough. As a workaround to truly stop consumption of messages, you can set the newly added [THREADS_PER_SUBSCRIPTION](https://mercadonarele.readthedocs.io/en/latest/api/settings.html#threads-per-subscription) setting to 1

**Comment by daaain** [comment]
Ah great, thanks a lot for the tip, it also worked with `worker = rele.Worker(subscriptions, threads_per_subscription=1)`.

What was the real issue for me though is that in development I had log level set to debug, which means the Google Pub/Sub library kept on pushing a lot of log messages, so even though the thread was paused there was still chatter.

Anyway, the issue is solved, so closing it.

**Comment by tobami** [comment]
Cool!
The google pub/sub library is super chatty even at the error level. The fix for that is that even if your app has INFO level, the google logger should be set to ERROR or even CRITICAL
