### ISSUE TITLE
Catch exceptions while waiting for futures result

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#159]
Our current way of publishing while `blocking`, or waiting, for a future could be a bit dangerous. This is because Google can raise errors like a [`TimeoutError`](https://github.com/python/cpython/blob/3.8/Lib/concurrent/futures/_base.py#L441). 

I would suggest to catch the error, and add another hook called `post_publish_failure`. 

In addition, we could add another parameter to publishing which would be like `raise_exception: bool`. If `True`, we wait but if the exception is raised, we silently fail and return a bool. If `False`, we can raise the exception.

**Comment by luisgc93** [comment]
> In addition, we could add another parameter to publishing which would be like raise_exception: bool. If True, we wait but if the exception is raised, we silently fail and return a bool. If False, we can raise the exception.

Wouldn't the opposite be more intuitive? So if `raise_exception` is `True` we should raise the exception and if `False` we fail silently 🤔
