### ISSUE TITLE
Publishing without boilerplate

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#177]
## Current Behaviour

Right now, if you want to call `rele.publish()`, you must call `config.setup()` before. This is so that 
`init_global_publisher` is called and setup properly. Otherwise a `ValueError` is raised.

## Proposal
I propose that a user should be able to call `rele.publish` without the boilerplate of `config.setup`. Instead, I think we can call `init_global_publisher` if publishing and there is no global publisher. The tough part will be getting the settings so that the credentials can be configured properly. 

But I do believe this can be solved, to make the UX more elegant and avoid boilerplate.

**Comment by tobami** [comment]
That would be great yes!

**Comment by EmilioCarrion** [comment]
I'll take a look into it
