### ISSUE TITLE
Worker initialization should raise an error on duplicate subscriptions

### ISSUE THREAD

**Issue by tobami** [mercadona/rele#180]
If two `subs` subscribe to the same topic and don't declare a suffix, stealing will happen where approximately half the messages will be processed by one subscription and half by the other. That's extremely difficult to test against and to debug in production, so a protection would be very useful.

I'd suggest raising an error straight away so the worker doesn't start. A warning log wouldn't be as effective because it could go unnoticed.

**Comment by EmilioCarrion** [comment]
I'll work on it 💪
