### ISSUE TITLE
Improve sub decorator

### ISSUE THREAD

**Issue by tbarbugli** [mercadona/rele#186]
The `sub` decorator can get some ease of use improvements

1. Use [functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps) to preserve `__name__` and `__doc__` of the original function
2. [Inspect](https://docs.python.org/3/library/functools.html#functools.wraps) callback function signature and raise an exception if the signature is not compatible (ie. missing `data`)
3. Log a warning message if the function cannot be discovered (ie. no `sub` in the path)

Slightly related to the second point: `@sub("topic", filter_by=42)` will raise a `TypeError` at runtime (because filters are used as callables but they are not checked)

**Comment by tobami** [comment]
Sounds like useful improvements :+1:

**Comment by andrewgy8** [comment]
Thanks @tbarbugli ! 

I second this change. One of the pain points right now is inspecting the signature of `@sub()`. As of now, we have to [explicitly set](https://github.com/mercadona/rele/blob/master/rele/subscription.py#L185) `args` both in the Subscription and the `sub`.

**Comment by EmilioCarrion** [comment]
I'll take a look into it
