### ISSUE TITLE
Filter by message attribute

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#35]
We would like to have our subscribers filter messages from a particular topic based on message attribute(s). For instance, we have one publisher publishing to topic `foobar`. The message is published with either attribute `location='backyard'` or `location='frontyard'`. 

If we have two subscribers listening to the same topic, one should only act on `location='backyard'`. 

I don't want to publish to two separate topics as they are publishing the same data type, only the location attribute changes from message to message. 

Additionally, we would like to globally define the filter value in the app. If we have two workers running the same subscriber, one should be able to filter the messages only for `backyard` messages and the other for `frontyard`. 

This is a proposal implementation:

```
# Scenario A (Local usage)

# subs.py
@sub('update_location', filter_by={'location': 'backyard'})
def update_location_backyard():
    pass

@sub('update_location', filter_by={'location': 'frontyard'})
def update_location_frontyard():
    pass
```

```
# Scenario B (Global Setting)

# settings.py
RELE_FILTER_BY={
    'update_location': {
        'location': 'frontyard'
    }
}

# subs.py
@sub('update_location', filter_by=settings.RELE_FILTER_BY)
def update_location():
    pass
```

**Comment by tobami** [comment]
In scenario B, does it make sense to set the `filter_by`? I understand "Global" as only needing to configure the global settings with a filter, no having to repeat myself in every `sub`.

For scenario A, a callable operating on the attributes would be more flexible, but more verbose:
```python
filter_by=labmda x: x['location'] == 'frontyard'
```
