### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#65]
We currently have flake8 in our linting command.  We do not have isort in the project style guidelines. 

Shall we add it? 

Or try out something new like [black](https://github.com/python/black)?

**Comment by daniel-ruiz** [comment]
I have no problem with undertaking either action. To me, black is something I wanted to try out. I see this project could be a good experimentation field for this. After all, it is widely used in other Python open-source projects.

**Comment by tobami** [comment]
I'd add isort, but not `black` yet. Not unless we have formatting problems.

**Comment by daniel-ruiz** [comment]
Why? I never used `black`, so I may have missed something. Do you see any drawbacks of using it at this point?

**Comment by tobami** [comment]
I asked Andrew what he meant and he didn't mean to use `black` for the autoformatting capabilities but as a substitute for flake8 for the reason that it has checks beyond what flake8 offers. In that case I'm OK with trying it out.

**Comment by edgarlatorre** [comment]
After quick read in the black documentation, IMHO I think it'd be kind of redundant. The differences from fake8 is that black would suggest changes to follow the defined style and for me it would work super well in a private project where you can have an agreement with the developer to use black integrated with you editor. For a open source project I wouldn't mind to have different styles if it does not have any pep8 offence. Also if we are not using auto format, it's kind of annoying to check the diffs with the suggestions.
