### ISSUE TITLE
Configurable serializer

### ISSUE THREAD

**Issue by tobami** [mercadona/rele#8]
Publishing serialization is done by DRF's `rest_framework.renderers.JSONRenderer`. It should be configurable and default to `json.dumps`

**Comment by andrewgy8** [comment]
Can we close this as it seems to be resolved with #82 and #83 ?

**Comment by tobami** [comment]
Do we keep track elsewhere to remove the dependency?

**Comment by andrewgy8** [comment]
I don't believe so. I recommend opening another issue called "Remove DRF dependency"
