### ISSUE TITLE
DEFAULT_ACK_DEADLINE should be moved to the Config Object

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#83]
In the publisher class, there is the use of DEFAULT_ACK_DEADLINE. 

I propose that this should be moved to the config object so it can be set via the settings dictionary.

**Comment by tobami** [comment]
I think you mean to make configurable, not "move"?

**Comment by andrewgy8** [comment]
The usage of it should be _altered_. And it should be configurable.
