### ISSUE TITLE
Global filter_by setting

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#86]
As user I would like to be able to filter all messages in my app. The implementation would allow me to avoid declaring the same `filter_by` attribute in every subscriber. 

In the case a global `filter_by` is defined and a subscriber `filter_by` is defined, I propose that the subscriber `filter_by` takes priority.

**Comment by andrewgy8** [comment]
Wait, this seems to have already been implemented. https://github.com/mercadona/rele/pull/72

I was looking through the code and found this https://github.com/mercadona/rele/blob/master/rele/management/commands/runrele.py#L40

I didnt find it in the current documentation. Is that because it will be in the next release @edgarlatorre ?

**Comment by edgarlatorre** [comment]
> Wait, this seems to have already been implemented. #72
> 
> I was looking through the code and found this https://github.com/mercadona/rele/blob/master/rele/management/commands/runrele.py#L40
> 
> I didnt find it in the current documentation. Is that because it will be in the next release @edgarlatorre ?

The `stable` documentation is build on release, but  you can find it in the latest https://mercadonarele.readthedocs.io/en/latest/guides/filters.html#global-filter maybe we can improve the filters documentation.

**Comment by andrewgy8** [comment]
I will close this since it will be in the next release. Thanks @edgarlatorre !
